# fly.toml
app = "thiwankas"

[build]
  # Using the Dockerfile in the repo; nothing else needed

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
